
name: docker-chezscheme-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/chezscheme/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/chezscheme:9.5-threads
        id: docker_build_chezscheme__9.5-threads
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/chezscheme/9.5-threads/
          tags: |
            chezscheme:9.5-threads
            chezscheme:9-threads
            chezscheme:threads
      -
        name: Build and push schemers/chezscheme:9.5-alpine
        id: docker_build_chezscheme__9.5-alpine
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/chezscheme/9.5-alpine/
          tags: |
            chezscheme:9.5-alpine
            chezscheme:9-alpine
            chezscheme:alpine
      -
        name: Build and push schemers/chezscheme:9.5
        id: docker_build_chezscheme__9.5
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/chezscheme/9.5/
          tags: |
            chezscheme:9.5
            chezscheme:9
            chezscheme:9-bullseye-slim
            chezscheme:latest
