
name: docker-chicken-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/chicken/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/chicken:5.3
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/chicken/5.3/
          tags: |
            schemers/chicken:5
            schemers/chicken:5.3
            schemers/chicken:5-bullseye-slim
            schemers/chicken:latest
