
name: docker-femtolisp-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/femtolisp/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/femtolisp:head-lambdaconservatory
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/femtolisp/head-lambdaconservatory/
          tags: |
            schemers/femtolisp:head-lambdaconservatory
            schemers/femtolisp:head-lambdaconservatory-bullseye-slim
      -
        name: Build and push schemers/femtolisp:head
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/femtolisp/head/
          tags: |
            schemers/femtolisp:head
            schemers/femtolisp:head-bullseye-slim
