
name: docker-gambit-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/gambit/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/gambit:head
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/gambit/head/
          tags: |
            gambit:head
            gambit:head-bullseye-slim
      -
        name: Build and push schemers/gambit:4
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/gambit/4/
          tags: |
            gambit:4
            gambit:4.9
            gambit:4-bullseye-slim
            gambit:latest
