
name: docker-guile-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/guile/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/guile:3
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/guile/3/
          tags: |
            schemers/guile:3
            schemers/guile:3.0
            schemers/guile:3-bullseye-slim
            schemers/guile:latest
      -
        name: Build and push schemers/guile:2
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/guile/2/
          tags: |
            schemers/guile:2
            schemers/guile:2.2
