
name: docker-ironscheme-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/ironscheme/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/ironscheme:1.0
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/ironscheme/1.0/
          tags: |
            schemers/ironscheme:1.0
            schemers/ironscheme:1
            schemers/ironscheme:1-bullseye-slim
            schemers/ironscheme:latest
      -
        name: Build and push schemers/ironscheme:1.0-mono
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/ironscheme/1.0-mono/
          tags: |
            schemers/ironscheme:1.0-mono
            schemers/ironscheme:mono
