
name: docker-kawa-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/kawa/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/kawa:head
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/kawa/head/
          tags: |
            schemers/kawa:head
            schemers/kawa:head-bullseye-slim
      -
        name: Build and push schemers/kawa:3.1
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/kawa/3.1/
          tags: |
            schemers/kawa:3.1
            schemers/kawa:3
            schemers/kawa:3-bullseye-slim
            schemers/kawa:latest
