
name: docker-ksi-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/ksi/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/ksi:3
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/ksi/3/
          tags: |
            ksi:3
            ksi:3-bullseye-slim
            ksi:latest
