
name: docker-loko-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/loko/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/loko:head
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/loko/head/
          tags: |
            schemers/loko:head
            schemers/loko:head-bullseye-slim
      -
        name: Build and push schemers/loko:0
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/loko/0/
          tags: |
            schemers/loko:0
            schemers/loko:0-bullseye-slim
            schemers/loko:latest
