
name: docker-scheme48-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/scheme48/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/scheme48:1.9
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/scheme48/1.9/
          tags: |
            schemers/scheme48:1.9
            schemers/scheme48:1
            schemers/scheme48:1-bullseye-slim
            schemers/scheme48:latest
