
name: docker-stklos-push-action

on:
  push:
    branches:
      - 'master'
    paths:
      - implementations/stklos/**/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/stklos:1
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/stklos/1/
          tags: |
            schemers/stklos:1
            schemers/stklos:1-bullseye-slim
            schemers/stklos:latest
      -
        name: Build and push schemers/stklos:head
        uses: docker/build-push-action@v2
        with:
          push: true
          context: implementations/stklos/head/
          tags: |
            schemers/stklos:head
            schemers/stklos:head-bullseye-slim
